#!/bin/sh

cd /app

cat <<EOF > .env
SD_BACKEND_URL=$SD_BACKEND_URL
SD_CLIENT_ID=$SD_CLIENT_ID
SD_AUTHORITY_URL=$SD_AUTHORITY_URL
SD_REDIRECT_URL=$SD_REDIRECT_URL
SD_LOGOUT_REDIRECT_URL=$SD_LOGOUT_REDIRECT_URL
SD_AUTH_SECRET=$SD_AUTH_SECRET
EOF

pnpm run build
pnpm start --port 80
