allowBuilds:
  core-js: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.1 || 26.0.0'
  - '@types/react@19.2.15'
  - postcss@8.5.15
  - core-js@3.50.0
  - vite@8.3.0
  - '@typescript-eslint/eslint-plugin@8.70.1'
  - '@typescript-eslint/parser@8.70.1'
  - '@typescript-eslint/project-service@8.70.1'
  - '@typescript-eslint/scope-manager@8.70.1'
  - '@typescript-eslint/tsconfig-utils@8.70.1'
  - '@typescript-eslint/type-utils@8.70.1'
  - '@typescript-eslint/types@8.70.1'
  - '@typescript-eslint/typescript-estree@8.70.1'
  - '@typescript-eslint/utils@8.70.1'
  - '@typescript-eslint/visitor-keys@8.70.1'
  - typescript-eslint@8.70.1
