allowBuilds:
  core-js: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.1 || 26.0.0'
  - '@types/react@19.2.15'
  - postcss@8.5.15
  - core-js@3.50.0
  - vite@8.3.0
  - '@typescript-eslint/eslint-plugin@8.70.1'
  - '@typescript-eslint/parser@8.70.1'
  - '@typescript-eslint/project-service@8.70.1'
  - '@typescript-eslint/scope-manager@8.70.1'
  - '@typescript-eslint/tsconfig-utils@8.70.1'
  - '@typescript-eslint/type-utils@8.70.1'
  - '@typescript-eslint/types@8.70.1'
  - '@typescript-eslint/typescript-estree@8.70.1'
  - '@typescript-eslint/utils@8.70.1'
  - '@typescript-eslint/visitor-keys@8.70.1'
  - typescript-eslint@8.70.1
  - '@fluentui/react-avatar@9.11.8'
  - '@fluentui/react-carousel@9.9.14'
  - '@fluentui/react-combobox@9.17.7'
  - '@fluentui/react-components@9.74.9'
  - '@fluentui/react-infolabel@9.4.27'
  - '@fluentui/react-menu@9.25.6'
  - '@fluentui/react-nav@9.4.7'
  - '@fluentui/react-persona@9.7.10'
  - '@fluentui/react-popover@9.14.9'
  - '@fluentui/react-positioning@9.23.3'
  - '@fluentui/react-spinbutton@9.6.7'
  - '@fluentui/react-table@9.19.22'
  - '@fluentui/react-tag-picker@9.10.5'
  - '@fluentui/react-tags@9.9.7'
  - '@fluentui/react-teaching-popover@9.7.7'
  - '@fluentui/react-tooltip@9.10.7'
  - '@fluentui/react-tree@9.16.8'
