name: check
on: push
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
          registry-url: "https://artifactory.devops.telekom.de/artifactory/api/npm/one-design-system-npm/"
          scope: "@telekom-ods"

      - name: Configure npm auth
        run: npm config set //artifactory.devops.telekom.de/artifactory/api/npm/one-design-system-npm/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint
