name: Docker Image Build on tag or release for CH version

on:
  push:
    tags:
      - "*"
  release:
    types: [published]

env:
  ORG: stackmon
  PROJECT: status-dashboard-v3-front

jobs:
  push_if_tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            "${{ secrets.REGISTRY }}/${{ env.ORG }}/${{ env.PROJECT }}"
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push ch-version
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}-ch
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          secrets: |
            SD_BACKEND_URL=${{ secrets.SD_BACKEND_URL_CH_PROD }}
            SD_CLIENT_ID=${{ secrets.SD_CLIENT_ID }}
            SD_AUTHORITY_URL=${{ secrets.SD_AUTHORITY_URL }}
            SD_ANALYTICS_URL=${{ secrets.SD_ANALYTICS_URL }}
            SD_ANALYTICS_ID=${{ secrets.SD_ANALYTICS_ID_PROD_CH }}
