name: Docker Image Build on tag or release

on:
  push:
    tags:
      - "*"
  release:
    types: [published]

env:
  ORG: opentelekomcloud
  PROJECT: status-dashboard-v3-api

jobs:
  push_if_tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            "${{ secrets.REGISTRY }}/${{ env.ORG }}/${{ env.PROJECT }}"
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          secrets: |
            SD_BACKEND_URL=${{ secrets.SD_BACKEND_URL }}
            SD_CLIENT_ID=${{ secrets.SD_CLIENT_ID }}
            SD_AUTHORITY_URL=${{ secrets.SD_AUTHORITY_URL }}
            SD_REDIRECT_URL=${{ secrets.SD_REDIRECT_URL }}
            SD_LOGOUT_REDIRECT_URL=${{ secrets.SD_LOGOUT_REDIRECT_URL }}
            SD_AUTH_SECRET=${{ secrets.SD_AUTH_SECRET }}
