name: Static Web Apps

on:
  push:
    branches:
      - master

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"

      - name: UseFile
        run: sed -i 's/SD_BACKEND_FILE=false/SD_BACKEND_FILE=true/' .env &&
          curl -o public/mock.json http://80.158.108.251:8000/v2/components &&
          curl -o public/event.json http://80.158.108.251:8000/v2/incidents

      - name: Build
        run: pnpm install && pnpm build

      - name: Pages Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          # cname: sd3.eco.tsi-dev.otc-service.com
          cname: sd.aloen.to
